### ISSUE TITLE
缺少文件

### ISSUE THREAD

**Issue by Kay7271** [Robin-WZQ/multimodel-emotion-recongnition-DEMO#2]
你好，请问预训练模型那边是不是忘记留下载链接了？

**Comment by Robin-WZQ** [comment]
因为项目还在继续完善当中，所以本想着等项目做完了再完善下相关资源。现在已经提交下载链接

**Comment by Robin-WZQ** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Robin-WZQ/multimodal-emotion-recognition-DEMO"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月24日(星期二) 凌晨2:28
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Robin-WZQ/multimodal-emotion-recognition-DEMO] 缺少文件 (#2)





 
你好，请问预训练模型那边是不是忘记留下载链接了？
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.


从QQ邮箱发来的超大附件

resnet-101-kinetics.pth (657.14M, 2021年09月23日 08:33 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=7d396138edd4dae2120f4bac4262051b535d515c015102041c09045a064f0303030d4c0001510419065b000f00555455090f035a64753746544a0f5d104f060400140a510a07435d524a4f48100a3709&code=19a8db74




save_30.pth (470.23M, 2021年09月23日 08:30 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=756136379723fad016571ca34463541d030502000100040518520406064e525101501b5551535f1f0200000756500701065006556268664154175368515348424109360a&code=5a67bcf2
